spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/voca
    username: root
    password: 123456

eureka:
  client:
    service-url:
      'local.zone': "http://localhost:8081/eureka/"
security:
  user:
    name: user
    password: password