pipeline {
    agent any
    stages{
        stage('Build') {
            steps {
                sh '''echo \"begin\"
cd router-service
pwd
cat /home/hirenloong/datasource > src/main/resources/application-prod.yml
cat /home/hirenloong/userinfo >> src/main/resources/application-prod.yml
gradle build -x test'''
            }
        }
        stage('Docker Build') {
            steps {
                sh '''cd router-service
docker build -t router-service .
docker stop router-service
docker rm router-service
docker create -p 8083:8083 -i -t --name router-service --network my-net voca
docker container start router-service'''
            }
        }
    }
}