pipeline {
    agent any
    stages{
        stage('Build') {
            steps {
                sh '''echo \"begin\"
cd router-service
pwd
cat /home/hirenloong/datasource >> src/main/resources/application-prod.yml
cat /home/hirenloong/userinfo >> src/main/resources/application-prod.yml
cat src/main/resources/application-prod.yml
gradle build -x test'''
            }
        }
        stage('Docker Build') {
            steps {
                sh '''cd router-service
pwd
docker build -t router-service --rm .
docker stop router-service | exit 0
docker rm router-service | exit 0
docker create -p 8083:8083 -i -t --name router-service --network my-net router-service
docker container start router-service'''
            }
        }
    }
}