pipeline {
    agent any
    stages{
        stage('Build') {
            steps {
                sh '''echo \"begin\"
cd english-service
pwd
cat /home/hirenloong/datasource > src/main/resources/application-prod.yml
cat /home/hirenloong/userinfo >> src/main/resources/application-prod.yml
cat src/main/resources/application-prod.yml
gradle build -x test'''
            }
        }
        stage('Docker Build') {
            steps {
                sh '''cd english-service
docker build -t english-service .
docker stop english-service | exit 0
docker rm english-service | exit 0
docker create -p 8082:8082 -i -t --name english-service --network my-net voca
docker container start english-service'''
            }
        }
    }
}