spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/voca
    username: root
    password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      'local.zone': "http://localhost:8082/eureka/"
  redis:
    host: localhost
    port: 6379
    password: