pipeline {
    agent any
    stages{
        stage('Build') {
            steps {
                sh '''echo \"begin\"
cd account-service
pwd
cat /home/hirenloong/datasource > src/main/resources/application-prod.yml
cat /home/hirenloong/userinfo >> src/main/resources/application-prod.yml
cat src/main/resources/application-prod.yml
gradle build -x test'''
            }
        }
        stage('Docker Build') {
            steps {
                sh '''cd account-service
docker build -t account-service .
docker stop account-service | exit 0
docker rm account-service | exit 0
docker create -p 8081:8081 -i -t --name account-service --network my-net voca
docker container start account-service'''
            }
        }
    }
}